name: 'esmeta'

on: [pull_request]

jobs:
  esmeta-typecheck:
    name: 'typecheck'
    runs-on: ubuntu-22.04

    env:
      ESMETA_HOME: vendor/esmeta

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup SBT
        uses: sbt/setup-sbt@v1
      - name: download esmeta
        run: |
          mkdir -p "${ESMETA_HOME}"
          cd "${ESMETA_HOME}"
          git init
          git remote add origin https://github.com/es-meta/esmeta.git
          git fetch --depth 1 origin 49ac09ee597701b421208398ca3ea69c2af62693 ;# v0.6.1
          git checkout FETCH_HEAD
      - name: build esmeta
        run: |
          cd "${ESMETA_HOME}"
          sbt assembly
      - name: link
        run: |
          rmdir "${ESMETA_HOME}"/ecma262 \
            && ln -s "$(pwd)" "${ESMETA_HOME}"/ecma262
      - name: typecheck
        run: '"${ESMETA_HOME}"/bin/esmeta tycheck -status -tycheck:log -tycheck:ignore=esmeta-ignore.json'


  esmeta-yet-steps:
    name: 'yet steps check'
    runs-on: ubuntu-22.04

    env:
      ESMETA_HOME: vendor/esmeta

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # we need to do some git-works
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup SBT
        uses: sbt/setup-sbt@v1
      - name: download esmeta
        run: |
          mkdir -p "${ESMETA_HOME}"
          cd "${ESMETA_HOME}"
          git init
          git remote add origin https://github.com/stonechoe/esmeta.git # using my repo for temp
          git fetch --depth 1 origin add8d5e3e976b643fd35716749c8507103af3990 ;
          git checkout FETCH_HEAD
      - name: build esmeta
        run: |
          cd "${ESMETA_HOME}"
          sbt assembly
      - name: link
        run: |
          rmdir "${ESMETA_HOME}"/ecma262 \
            && ln -s "$(pwd)" "${ESMETA_HOME}"/ecma262
      - name: gen filter
        run: '"${ESMETA_HOME}"/bin/esmeta extract -status -extract:log -extract:target=${{ github.event.pull_request.base.sha }}'
      - name: copy log file
        run: 'cp "${ESMETA_HOME}"/logs/extract/yet-steps "${ESMETA_HOME}"/yet-steps-manual.json'
      - name: typecheck
        run: '"${ESMETA_HOME}"/bin/esmeta extract -status -extract:warn-action -extract:target=${{ github.event.pull_request.head.sha }} -extract:ignore-yets="${ESMETA_HOME}/yet-steps-manual.json"'

