name: 'ecma-262'

on:
  pull_request_target:
    branches:
       - '*'
  push:
    branches:
       - main

jobs:
  build:
    name: 'check IPR form'
    runs-on: ubuntu-22.04

    steps:
      - name: Skip IPR
        run: echo "skipped"
